<a href="https://colab.research.google.com/github/rreghunandan/Tasks/blob/main/Task2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__, np.show_config

('1.21.5', <function numpy.__config__.show>)

In [ ]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z.size

10

In [ ]:
z.itemsize

8

In [ ]:
np.info(np.add)
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [ ]:
z1=np.zeros(10)
z1[5]=1
z1

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [ ]:
z2=np.arange(10,49)
z2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
z2=z2[::-1]
z2


array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [ ]:
z3=np.arange(9).reshape(3,3)
z3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
z4=np.nonzero([1,2,0,0,4,0])
z4

(array([0, 1, 4]),)

In [ ]:
I=np.ones((3,3))
I

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
R=np.random.random((3,3,3))
R

array([[[0.30218871, 0.06912526, 0.22231889],
        [0.36942314, 0.06689747, 0.50020064],
        [0.54132924, 0.00949055, 0.16656401]],

       [[0.23798166, 0.8788902 , 0.747591  ],
        [0.41822195, 0.81552426, 0.27812517],
        [0.03227537, 0.75396149, 0.20569935]],

       [[0.76863734, 0.24736948, 0.64114022],
        [0.21982595, 0.87912849, 0.91693859],
        [0.4404959 , 0.78873862, 0.28062125]]])

In [ ]:
R=np.random.random((10,10))
R.min(),R.max()


(0.02020157726716887, 0.9781025420894217)

In [ ]:
R=np.random.randint(20,size=30)
R.mean()

8.466666666666667

In [ ]:
Q=np.ones((10,10))
Q[1:-1,1:-1]=0
Q

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
Q=np.pad(Q,pad_width=1,mode="constant",constant_values=000)
Q

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
a=0 * np.nan
a

nan

In [ ]:
b=np.nan == np.nan
b

False

In [ ]:
c=np.inf > np.nan
c

False

In [ ]:
d=np.nan - np.nan
d

nan

In [ ]:
e=0.3 == 3 * 0.1
e

False

In [ ]:
w=np.zeros((5,5))
w

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
w=np.diag([1,2,3,4],-1)
w

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
Check = np.zeros ((8,8))
Check[1::2, ::2]= 1
Check[::2, 1::2] = 1
print (Check)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?    #not done#

In [ ]:
a=np.unravel_index(100,(6,7,8))      #cordinates of 100
a


(1, 5, 4)

In [ ]:
a = np.zeros((8,8))
j=np.tile(a, (0,1))
j
#Create a checkerboard 8x8 matrix using the tile function        #not done

array([], shape=(0, 8), dtype=float64)

In [ ]:
t = np.random.random((5,5))        #converting to absolute value ie vector magnitude of 1
t = (t - np.mean (t)) / (np.std (t))
print(t)

[[-0.82732846  0.23971192 -1.1768925  -1.18029316  0.93246547]
 [ 0.93901604 -0.9900594   0.51174012 -1.10760527 -0.26528334]
 [ 0.21999471 -0.48397252 -1.06836911  0.41951657 -0.95781514]
 [ 0.66333196  1.48523365 -1.14508389  1.83073782  1.95679603]
 [ 1.49592504  0.12728955 -0.33649405 -1.05628024 -0.22628179]]


In [ ]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA) not done

In [ ]:
Mat = np.ones((5,3)) @ np.ones((3,2))
Mat

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] = -1
print(Z)

[ 0  1  2  3 -1 -1 -1 -1 -1  9 10]


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
#Consider an integer vector Z, which of these expressions are legal?  not done 
'''
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
'''

'\nZ**Z\n2 << Z >> 2\nZ <- Z\n1j*Z\nZ/1/1\nZ<Z>Z\n'

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [ ]:
Round = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Round)), Round))

[  3.   7.  -9.  -6.   1. -10.  -8.  -5.  -3.  -5.]


In [ ]:
R1 = np.random.randint(0,10,10)
R2 = np.random.randint(0,10,10)
print(np.intersect1d(R1,R2))

[2 5 7 8 9]


In [ ]:
 #How to ignore all numpy warnings (not recommended) not done.

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [ ]:
Yester =np.datetime64('today','D') - np.timedelta64(1,"D")
today     = np.datetime64('today')
tomorrow =np.datetime64('today','D') + np.timedelta64(1,"D")
print(Yester,today,tomorrow)

2022-02-17 2022-02-18 2022-02-19


In [ ]:
Yester =np.datetime64('today','Y') - np.timedelta64(1,"Y")
today     = np.datetime64('today','Y')
tomorrow =np.datetime64('today','Y') + np.timedelta64(1,"Y")
print(Yester,today,tomorrow)

2021 2022 2023


In [ ]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [ ]:
A=[1,2,3]
B=[5,67]
#Val=np.sum([1,2,3],[5,6,7])
#35. How to compute ((A+B)\*(-A/2)) in place (without copy)?    not done 


In [ ]:
Z = np.random.uniform(0,10,10)
Z

array([1.83889996, 6.68787529, 7.10585892, 9.60064369, 9.82065318,
       9.89733552, 0.08901555, 5.59104265, 7.99337387, 9.35941494])

In [ ]:
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[1. 6. 7. 9. 9. 9. 0. 5. 7. 9.]
[1. 6. 7. 9. 9. 9. 0. 5. 7. 9.]
[1. 6. 7. 9. 9. 9. 0. 5. 7. 9.]
[1 6 7 9 9 9 0 5 7 9]
[1. 6. 7. 9. 9. 9. 0. 5. 7. 9.]


In [ ]:
z3=np.zeros((5,5))
z3=z3+np.arange(5)
z3


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [ ]:
def generate():
  for i in range(10):
    yield i

Q = np.fromiter(generate(),dtype=int)
Q

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Z = np.linspace(0,1,11,endpoint=True)[1:-1]
Z

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
a = np.random.random(10)
a.sort()
a

array([0.04369773, 0.12311146, 0.18183288, 0.18609469, 0.27113581,
       0.63541366, 0.72587568, 0.75105417, 0.86566707, 0.95805592])

In [ ]:
a=np.arange(10)
l=np.add.reduce(a)
l

45

In [ ]:
All=np.allclose([1, 2], [2,1])
Eql=np.array_equal([4,5,6],[4,5,6])
print(All)
print(Eql)

False
True


In [ ]:
a = np.zeros(10)
a.flags.writeable = False
a[0]=5

ValueError: ignored

In [ ]:
m= np.random.random(10)
print(m)
m[Z.argmax()] = 0
m

[0.37088597 0.47926934 0.40945325 0.59629413 0.80327844 0.93823868
 0.94425048 0.55304176 0.94806346 0.97700953]


array([0.37088597, 0.47926934, 0.40945325, 0.59629413, 0.80327844,
       0.93823868, 0.94425048, 0.55304176, 0.        , 0.97700953])

In [ ]:
a= np.zeros((5,5), [("x",int),("y",int)])     
a["x"],a["y"]  = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
a             

array([[(0, 0), (0, 0), (0, 0), (0, 0), (1, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0), (1, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0), (1, 0)],
       [(0, 0), (0, 0), (0, 0), (0, 0), (1, 0)],
       [(0, 1), (0, 1), (0, 1), (0, 1), (1, 1)]],
      dtype=[('x', '<i8'), ('y', '<i8')])

In [ ]:
for dtype in [np.int8, np.int32]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647


In [ ]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
np.set_printoptions
A = np.zeros((5,5))
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#How to find the closest value (to a given scalar) in a vector?  not done

In [ ]:
a = np.zeros(5, [ ('position', [ ('x', int),
                                   ('y', int)]),
                    ('color',    [ ('r', int),
                                   ('g', int),
                                   ('b', int)])])
print(a)
a

[((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))]


array([((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0)),
       ((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0))],
      dtype=[('position', [('x', '<i8'), ('y', '<i8')]), ('color', [('r', '<i8'), ('g', '<i8'), ('b', '<i8')])])

In [ ]:
x = np.arange(6, dtype=np.float32)
x = x.astype(np.int32, copy=False)
print(x)
x

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5], dtype=int32)

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
fak = np.genfromtxt(s, delimiter=",", dtype=np.int32)
fak

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int32)

In [ ]:
#Generate a generic 2D Gaussian-like array

In [ ]:
n = 10
place=15
R = np.zeros((n,n))
np.put(R, np.random.choice(range(n*n), place, replace=False),8)
R

array([[0., 0., 0., 8., 0., 0., 0., 0., 0., 0.],
       [0., 0., 8., 0., 0., 0., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0., 0., 0., 8., 0., 8.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0., 0., 0., 8., 0., 0.],
       [0., 0., 8., 0., 8., 0., 0., 0., 0., 8.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 8., 8., 0., 0., 8., 0., 0., 0., 0.],
       [8., 0., 0., 8., 0., 0., 0., 0., 0., 0.]])

In [ ]:
X = np.random.rand(4,3)
Y = X - X.mean(axis=0, keepdims=True)
Y

array([[ 0.51129511, -0.18787457,  0.02087669],
       [-0.01949156, -0.23198821,  0.02564009],
       [-0.20722126,  0.56162468, -0.01620427],
       [-0.28458228, -0.14176189, -0.0303125 ]])

In [ ]:
sou = np.random.randint(0,6,(3,3))
print(sou)
u=(sou[sou[:,1].argsort()])
u


[[4 5 4]
 [5 2 2]
 [5 4 1]]


array([[5, 2, 2],
       [5, 4, 1],
       [4, 5, 4]])

In [ ]:
null = np.random.randint(0,3,(3,4))
l=((~null.any(axis=1)).any())
l

True

In [ ]:
NV = np.random.randint(0,10,2)
print(NV)
v = 1
m = NV.flat[np.abs(NV - v).argmin()]
m


[4 2]


2

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
nit = np.nditer([A,B,None])
for x,y,z in nit:
  s=[x+y+z]
print(A)
print(B)
s


[[0]
 [1]
 [2]]
[[0 1 2]]


[5]

In [ ]:
 #Create an array class that has a name attribute  not done

In [ ]:
#m = np.zeros(10)
#new=np.random.random((0,10))
#Z=np.bincount(m,I,1)
#Z



In [ ]:
array2 = [10, 11, 4, 6, 2, 1, 9]                                                                                                                                                                                                                                             
array1 = [1, 3, 1, 3, 1, 2, 2]
bin = np.bincount(array1, array2)
bin


array([ 0., 16., 10., 17.])

In [ ]:
A = np.random.randint(0,10,(4,3,3,2))
sum = A.sum(axis=(-2,-1))
sum


array([[25, 21, 35],
       [24, 27, 30],
       [22, 29, 29],
       [27, 19, 38]])

In [ ]:
V = np.array([1,2,3,4,5])
nv = 3
V1 = np.zeros(len(V) + (len(V)-1)*(nv))
V1[::nv+1] = V
V1

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
pro=A * B[:,:,None]
pro

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

In [ ]:
A = np.arange(10).reshape(5,2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
A[[0,1]] = A[[1,0]]
A

array([[2, 3],
       [0, 1],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:

a1 = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(a1)), a1)
a

array([1, 1, 2, 3, 4, 4, 6])

In [ ]:
#How to compute averages using a sliding window over an array?

In [ ]:
#Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]

In [ ]:
Z = np.arange(1,15,dtype=np.int32)
R = stride_trick.as_strided(Z,(11,4),(4,4))
R

NameError: ignored

In [ ]:
m = np.random.randint(0,10,10)
print(m)
count=np.bincount(m).argmax()
count


[1 1 6 7 9 4 5 1 5 6]


1

In [ ]:
lar = np.arange(60)
np.random.shuffle(lar)
n = 3
lar[np.argsort(lar)[-n:]]


array([57, 58, 59])

In [ ]:
lar[np.argpartition(-lar,n)[:n]]

array([59, 58, 57])